#!/bin/bash
# mkshz - create a shell script with an embedded tgz archive
# Author: joknarf
#
[ ! "$2" ] && cat - <<'EOF' >&2 && exit 1
usage: mkshz <file.shz> <dir> [<command> [--tmp-exec] [--pre-extract <command>] <tar options>]

Creates a shell script <file.shz> with embedded tgz archive created from <dir> content.
o The script will extract the archive to the current directory on execution.
o A <command> in <dir> can be specified to run after extraction with arguments passed to <file.shz>.
o A pre-extract <command> in <dir> can be specified to be extracted and run before the whole archive is extracted.
o if `--tmp-exec` flag is set the resulting script will extract to /tmp/shz.XXXX executes the commands and clean the /tmp/shz.XXXXX
o shz_version environment variable can be set to get the version of the archive using 'v-shz' parameter.

Example usage:
$ shz_version=v1.2 mkshz install.shz app/ bin/config.sh --pre-extract bin/pre-stop.bash --exclude=.git --exclude=*.o

Notes:
o The <command> arguments are relative to <dir>.
o The script generated will be created with a shebang line for bash.
o The pre-extract <command> will be extracted and executed before extracting whole archive
o The pre-extract <command> does not receive any arguments.
o If the pre-extract <command> exit code is not zero, the script will abort whole extraction.
EOF
version=${shz_version:-1.0}
shz="$1"
dir="${2%/}"
cmd="${3#./}"
shift 3
[ "$1" = "--tmp-exec" ] && tmpexec=1 && shift || tmpexec=""
[ "$1" = "--pre-extract" ] && pre="${2#./}" && shift 2 || pre=""

[ ! -d "$dir" ] && echo "Error: Directory $dir does not exist" >&2 && exit 1
[ "$cmd" ] && cmd="$dir/$cmd" && [ ! -x "$cmd" ] && echo "Error: Command '$cmd' not found or not executable" >&2 && exit 1
[ "$pre" ] && pre="$dir/$pre" && [ ! -x "$pre" ] && echo "Error: Pre-extract commmand '$pre' not found or not executable" >&2 && exit 1

tar=$(command -v gtar tar)
tar="${tar%%$'\n'*}"

(
  sed -e '1,/^__tpl__/d' \
      -e "s#<dir>#$dir#" \
      -e "s#<pre>#$pre#" \
      -e "s#<cmd>#$cmd#" \
      -e "s#<shz>#${shz##*/}#" \
      -e "s#<version>#$version#" \
      -e "s#<tmpexec>#$tmpexec#" "$0"
  $tar cvzf - "$@" "$dir"
) >"$shz" || { echo "Error: Failed to create $shz" >&2; exit 1; }
chmod +x "$shz"
printf '\n%s\n' "$shz created with embedded tgz archive from '$dir'"
exit 0

__tpl__ ======= self-extracting shell script template starts here =================================
#!/bin/bash
# Script created with mkshz
# This script extracts embedded tgz archive 
# extract archive directory: '<dir>'
# pre-extract command: '<pre>'
# post-extract command: '<cmd>'
# to extract the archive without command execution, use:
#  ./<shz> x-shz
# shz_verbose=1 env variable can be set to enable tar output
# shz_target_dir can be set to specify the target directory for extraction
#
version="<version>"
dir="<dir>"
pre="<pre>"
cmd="<cmd>"
tmpexec="<tmpexec>"
shz="${0##*/}"
[ "$shz_verbose" ] && v=v || v=""
[ "$1" = "v-shz" ] && echo "$version" && exit 0
[ "$1" = "x-shz" ] && cmd="" pre=""

[ ! "$shz_target_dir" ] && [ "$tmpexec" ] && {
  shz_target_dir=$(mktemp -d /tmp/shz.XXXXXX) || exit 1
  [ "$cmd" ] && trap 'echo "$shz: Cleaning up temporary directory: $shz_target_dir" >&2; rm -rf "$shz_target_dir"' EXIT
}
: ${shz_target_dir:=$PWD}

extract() {
  sed '1,/^__tgz__/d' "$0"| (cd "$shz_target_dir" && tar xz${v}f - "$@" >&2) || exit 1
}

# Pre-extract script:
[ "$pre" ] && {
  echo "$shz: Extracting/Executing pre-extract script: $pre" >&2
  extract "$pre"
  "$shz_target_dir/$pre" || { echo "$shz: Error: Failed to execute pre-extract script ($pre)" >&2; exit 1; }
}
echo "$shz: Extracting archive directory '$dir' in '$shz_target_dir'" >&2
extract
[ "$cmd" ] || exit 0
cmd="$shz_target_dir/$cmd"
echo "$shz: Executing command: $cmd $*" >&2
[ ! -x "$cmd" ] && echo "$shz: Error: Command $cmd not found or not executable." >&2 && exit 1
"$cmd" "$@"
exit $?

__tgz__ ====== binary data starts here ==========================================
